name: sneaker_shop
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  intl: ^0.18.1
  cloud_firestore: ^4.7.1
  firebase_storage: ^11.0.15
  google_sign_in: ^6.0.2
  shared_preferences: ^2.0.20
  firebase_database: ^10.1.0
  carousel_slider: ^4.2.1
  google_nav_bar: ^5.0.6
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - lib/images/
