// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCR-5nGz6cMZ3KWhssxDxTOw4LGDXKh1O0",
    authDomain: "sneakershop-bb61a.firebaseapp.com",
    databaseURL: "https://sneakershop-bb61a-default-rtdb.firebaseio.com",
    projectId: "sneakershop-bb61a",
    storageBucket: "sneakershop-bb61a.appspot.com",
    messagingSenderId: "223976152027",
    appId: "1:223976152027:web:12114db3a76a00a84665fe",
    measurementId: "G-ZV2M6XB5GT",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR-5nGz6cMZ3KWhssxDxTOw4LGDXKh1O0',
    appId: '1:223976152027:android:7762505b9d28d6904665fe',
    messagingSenderId: '223976152027',
    projectId: 'sneakershop-bb61a',
    databaseURL: 'https://sneakershop-bb61a-default-rtdb.firebaseio.com',
    storageBucket: 'sneakershop-bb61a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR-5nGz6cMZ3KWhssxDxTOw4LGDXKh1O0',
    appId: '1:223976152027:android:7762505b9d28d6904665fe',
    messagingSenderId: '223976152027',
    projectId: 'sneakershop-bb61a',
    databaseURL: 'https://sneakershop-bb61a-default-rtdb.firebaseio.com',
    iosClientId:
        '388765248192-orr2cjqo6p70hj0pqe9th9ui8njejb4f.apps.googleusercontent.com',
    iosBundleId: 'com.example.newapps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR-5nGz6cMZ3KWhssxDxTOw4LGDXKh1O0',
    appId: '1:223976152027:android:7762505b9d28d6904665fe',
    messagingSenderId: '223976152027',
    projectId: 'sneakershop-bb61a',
    databaseURL: 'https://sneakershop-bb61a-default-rtdb.firebaseio.com',
    iosClientId:
        '388765248192-orr2cjqo6p70hj0pqe9th9ui8njejb4f.apps.googleusercontent.com',
    iosBundleId: 'com.example.newapps',
  );
}
